### ISSUE TITLE
blindRotate bit errors in testMKbootNAND test scenarios

### ISSUE THREAD

**Issue by strongX509** [ilachill/MK-TFHE#3]
If the number of trials is increased from 100 to 1000 in the [testMKbootNAND_FFT_details](https://github.com/ilachill/MK-TFHE/blob/master/src/test/testMKbootNAND_FFT_details.cpp#L106) test scenario using the external **FFTW** library then 5 decryption errors occur after the blindRotate operation as the following log excerpt shows [testMKbootNAND_FFT_details-fftw.log](https://github.com/ilachill/MK-TFHE/files/3317605/testMKbootNAND_FFT_details-fftw.log)

_A bit error rate of 0.5% is just not acceptable for any serious multi-key application, so I'm hoping either for a fix in the MK-THFE software implementation or in the blindRotate algorithm itself._

The same 5 decryption errors also occur if the non-FFT version [testMKbootNAND](https://github.com/ilachill/MK-TFHE/blob/master/src/test/testMKbootNAND.cpp#L53) is used. 

If alternatively the built-in **spqlios-avx** and **nayuki-avx** FFT implementations are used then even 12 and 15 errors, respectively, occur.

**Comment by ilachill** [comment]
Our email exchange solved the issue. Thanks again for your interest in the project!
