### ISSUE TITLE
Beyond 1 bit encryption and decryption for Multi-key?

### ISSUE THREAD

**Issue by send2cny** [ilachill/MK-TFHE#7]
Using existing NAND operator function provided, 
we pass in a integer value 2 instead of 1
we get this:

Message 1:  clear = 2, decrypted = 1
Message 2:  clear = 2, decrypted = 1

How can we pass in value beyond 1 bit?

**Comment by ilachill** [comment]
NAND is a binary gate and it is not built to work with messages different from binary, so you cannot pass values beyond 1 bit. If you want to evaluate a function on larger inputs, you have to express it as a Boolean circuit and evaluate it as a composition of bootstrapped gates.

**Comment by send2cny** [comment]
This happens even before the gate evaluation code.
What we meant here is the encryption and decryption part of the code.

testMKbootNAND_FFT_v2.cpp

When we pass "**value = 2**" into mess1 
MKbootsSymEncrypt(test_in1, mess1, MKlwekey);

We are expecting  "**value = 2**" as an output
  // verify encrypt 
int32_t mess1_dec = MKbootsSymDecrypt(test_in1, MKlwekey);
cout << "Message 1: clear = " << mess1 << ", decrypted = " << mess1_dec << endl;
But instead the output is "**1**" which is not correct.


We will not be able to build any Boolean circuit if the input is wrong in the first place.

**Comment by ilachill** [comment]
This is because also the encryption is binary, just 0 and 1 are accepted. 
You can see it by checking the functions bootsSymEncrypt and bootsSymDecrypt in MK-TFHE/src/libtfhe/tfhe_gate_bootstrapping.cpp

**Comment by send2cny** [comment]
Yup! we sorted this.
